server:
  port: 8000

spring:
  mail:
    username: chunfengh163@163.com
    host: smtp.163.com
    password: OYZDLGLUUOLFGOEV
  #    port: 587
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vhr?serverTimezone=Asia/Shanghai
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:SS
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
      resolve-lazily: true
  main:
    allow-circular-references: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true
    jdbc-type-for-null: null
    local-cache-scope: statement
  mapper-locations: classpath:/mapper/**/*.xml
#  type-aliases-package: com.rufeng.healthman.pojo
vhr:
  work-dir: ${user.home}/.vhr